config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root 'pages#home'
  resources :pools, except: [:destroy] do
    get 'agendas' => 'pools#availability'
    resources :agendas, only: :create
  end
  get 'searchjson' => 'pools#searchjson'
  resources :users, except: [:index, :destroy] do
    get 'bookings' => 'users#bookings'
    get 'my-pools' => 'users#pools'
  end
  resources :bookings, except: [:destroy] do
    post 'cancel' => 'bookings#cancel'
    post 'pay' => 'bookings#pay'
    post 'accept' => 'bookings#accept'
    post 'reject' => 'bookings#reject'
  end
  require "sidekiq/web"
    mount Sidekiq::Web => '/sidekiq'
end

app/models/pool.rb
class Pool < ActiveRecord::Base
  belongs_to :user
  has_many :agendas
  has_many :bookings
  has_attachments :photos, minimum: 1, maximum: 5

  validates :width, :length, :depth, :shape, :location, :water_type, :equipments, :description, :price, :title, :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def average_rating
    bookings.map(&:booking_rating).reject(&:nil?).reduce(:+).fdiv(bookings.map(&:booking_rating).reject(&:nil?).size) unless bookings.map(&:booking_rating).reject(&:nil?).empty?
  end

  def nb_booking_comment
    return bookings.map(&:booking_comment).reject(&:nil?).count unless bookings.empty?
    return 0
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index, :show, :searchjson]
  before_action :find_pool, only: [:show, :edit, :update]

  def index
    if !params.has_key?(:location) || params[:location].empty?
      @pools = Pool.all
    else
      @location = params[:location].downcase
      @pools = search_pools_by_location
    end
    if params.has_key?(:reservation_date) && !params[:reservation_date].empty?
      reservation_string = params[:reservation_date].gsub('%2F','/')
      @reservation_date = date_string_to_date(reservation_string)
      @pools = fetch_pools_by_availability
    end
    # Let's DYNAMICALLY build the markers for the view.
    @markers = Gmaps4rails.build_markers(@pools) do |pool, marker|
      @pool = pool
      marker.lat pool.latitude
      marker.lng pool.longitude
      marker.infowindow render_to_string(partial: "pool_infowindow", :locals => { :object => pool}).gsub(/\n/, '')
      marker.picture url: ActionController::Base.helpers.asset_path("goutte-deau-icon.png"), width: 38, height: 50#, shadow_width: "20", shadow_height: "50", shadow_anchor: [5, 10]
    end
  end

  def availability
    @pool = Pool.find(params[:pool_id])

    @agenda = Agenda.new
    @agendas = Agenda.where('pool_id = ?', @pool.id)
    @agendas = @agendas.reject{ |a| date_string_to_date(a.start_date) < Date.today }
  end

  def show
    @booking = Booking.new
    find_pool
    get_available_booking_dates
    get_all_available_hours
  end

  def edit
  end

  def update
    if @pool.update(pool_params)
      redirect_to pool_path(@pool)
    else
      render :edit
    end
  end

  def new
    @pool = Pool.new
    @pool.user = current_user
  end

  def create
    @pool = Pool.new(pool_params)
    @pool.user = current_user
    if @pool.save
      redirect_to pool_path(@pool)
    else
      @show_modale = true
      @pools = Pool.where("user_id = #{current_user.id}")
      render "users/pools"
    end
  end

  def searchjson
    if !params.has_key?(:location) || params[:location].empty?
      @pools = Pool.all
      if params.has_key?(:max_price) && !params[:max_price].empty?
        max_price = params[:max_price].to_i
        @pools = @pools.where("price > ?", max_price)
      end
    else
      @location = params[:location].downcase
      range = 50 if params[:range].empty?
      range = params[:range].to_i
      @pools = Pool.where('id NOT IN (?)', Pool.near(@location, range).map{ |e| e.id } )
      if params.has_key?(:max_price) && !params[:max_price].empty?
        max_price = params[:max_price].to_i
        p max_price
        @pools = Pool.where('price > ? OR id NOT IN (?)', max_price, Pool.near(@location, range).map{ |e| e.id } )
      end
    end
    @markers = Gmaps4rails.build_markers(@pools) do |pool, marker|
      @pool = pool
      marker.lat pool.latitude
      marker.lng pool.longitude
      marker.infowindow render_to_string(partial: "pool_infowindow", :locals => { :object => pool}).gsub(/\n/, '')
      marker.picture url: ActionController::Base.helpers.asset_path("goutte-deau-icon.png"), width: 38, height: 50#, shadow_width: "20", shadow_height: "50", shadow_anchor: [5, 10]
    end
    @ids = @pools.select("id")
    render :searchjson, :layout => false
  end

  private

  def get_available_booking_dates
    init_agenda = Agenda.where('pool_id = ?', @pool.id) || []
    @agendas = init_agenda.map { |a| [a.start_date, a.end_date] }.map do |couple|
      date_range = (Date.parse(couple[0])..Date.parse(couple[1])).map(&:to_s)
    end
    @agendas = @agendas.flatten.map { |d| d.split('-').reverse.join('/') }
    @all = (Date.parse('01/01/2016')..Date.parse('31/12/2016')).map(&:to_s).flatten.map { |d| d.split('-').reverse.join('/') }
    @final = @all - @agendas
  end

  def get_all_available_hours
    @unavailable_slots = {}
    @agendas.each do |day|
      slots = Booking.where('pool_id = ? AND DATE = ? AND status <> ?', @pool.id, day, 'cancelled').map { |s| [s.start_time, s.end_time] }
      @unavailable_slots[day] = slots unless slots.empty?
    end
  end

  def find_pool
    @pool = Pool.find(params[:id])
  end

  def pool_params
    params.require(:pool).permit(:user_id, :width, :length, :depth, :shape, :location, :water_type, :address, :latitude, :longitude, :equipments, :price, :description, :status, :title, photos: [])
  end

  def search_pools_by_location
    return Pool.near(@location, 50)
  end

  def fetch_pools_by_availability
    results = []
    @pools.each do |pool|
      pool.agendas.each do |agenda|
        results << pool if ( @reservation_date >= date_string_to_date(agenda.start_date) &&  @reservation_date <= date_string_to_date(agenda.end_date))
      end
    end
    return results
  end

  def date_string_to_date(date_string)
    date_array = date_string.split('/')
    return Date.new(date_array[2].to_i, date_array[1].to_i, date_array[0].to_i)
  end

end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/views/pools/_owner_pool_card.html.erb
<div class="card-container">
  <%= link_to pool_path(pool), :class => "card-link" do %>
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= pool.photos? ? cl_image_path(pool.photos.first.path) : image_path('barcelona_pool.jpg') %>);">
  </div>
  <div class="card-footer">
    <h5><%= pool.title %></h5>
    <p style="margin: 0 0 5px"><%= pool.description %></p>
    <div class="rating">
      <% unless pool.average_rating.nil? then pool.average_rating.round.times do %>
        <i class="fa fa-star" aria-hidden="true"></i>
      <% end %>
      <% (5 - pool.average_rating.round).times do %>
        <i class="fa fa-star-o" aria-hidden="true"></i>
      <% end %>
      <% end %>
    </div>
  </div>
  <div class="price-tag">
    <p><%= pool.price %> €</p>
  </div>
  <% end %>
  <div class="edit-link">
  <%= link_to "Edit my pool", user_my_pools_path(current_user) + "?pool_id=#{pool.id}", class: 'btn btn-success'  %>
  <%= link_to "Manage pool availability", pool_agendas_path(pool), class: 'btn btn-primary'  %>
  </div>
</div>

app/views/pools/_pool_card.html.erb
<div class="card-container">
  <%= link_to pool_path(pool), :class => "card-link" do %>
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= pool.photos? ? cl_image_path(pool.photos.first.path) : image_path('barcelona_pool.jpg') %>);">
  </div>
  <div class="card-footer">
    <h5><%= pool.title %></h5>
    <p style="margin: 0 0 5px"><%= pool.description %></p>
    <div class="rating">
      <% unless pool.average_rating.nil? then pool.average_rating.round.times do %>
        <i class="fa fa-star" aria-hidden="true"></i>
      <% end %>
      <% (5 - pool.average_rating.round).times do %>
        <i class="fa fa-star-o" aria-hidden="true"></i>
      <% end %>
      <% end %>
    </div>
  </div>
  <div class="card-avatar">
    <% if pool.user.avatar? %>
      <%= cl_image_tag pool.user.avatar.path, class: 'avatar-bordered', id: pool.user.id %>
    <% end %>
  </div>
  <div class="price-tag">
    <p><%= pool.price %> €</p>
  </div>
  <% end %>
</div>

app/views/pools/_pool_form.html.erb
<div class="pools">
  <div class="container">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">
        <div class="pool">
          <%= simple_form_for(@pool) do |f| %>
            <%= f.error_notification %>

            <%= f.input :title %>
            <%= f.input :description %>
            <%= f.input :location %>
            <%= f.input :width %>
            <%= f.input :length %>
            <%= f.input :depth %>
            <%= f.input :shape %>
            <%= f.input :water_type %>
            <%= f.input :equipments %>
            <%= f.input :price %>
            <%= f.input :photos, as: :attachinary %>

            <%= f.button :submit %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pools/_pool_infowindow.html.erb
<h4><%= link_to @pool.title, pool_url(@pool), style: 'text-decoration: none' %></h4>
<h4 style="text-align: center;"><strong><%= @pool.price %> €</strong></h4>

app/views/pools/_search_form.html.erb
<form action="/pools/search/json" method="POST" class="form-inline">
  <div class="col-xs-3 form-group">
    <p style="font-size: 14px"><%= @location.nil? ? "" : "You are in : #{@location.capitalize} " %><br><%= link_to "Change location", root_path %></p>
  </div>
  <div class="col-xs-3 form-group justmargin">
    <div class="input-group">
      <input type="number" class="form-control" name="search_parameters[max_price]" id="max-price" placeholder="max">
      <div class="input-group-addon">€</div>
    </div>
  </div>
  <div class="col-xs-3 form-group justmargin">
    <div class="input-group">
      <input type="number" class="form-control" name="search_parameters[range]" id="range" placeholder="max">
      <div class="input-group-addon">km</div>
    </div>
  </div>
  <button type="submit" class="col-xs-1 btn btn-success" style="margin: 0px 10px;" id="search-submit">Filter</button>
  <button type="submit" class="col-xs-1 btn btn-primary" id="reset-filter">Reset</button>
</form>

app/views/pools/availability.html.erb
<div class="container" id="#availability-datepicker">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= simple_form_for [@pool, @agenda] do |f| %>
      <div class="col-xs-10">
      <%= f.input :start_date, label: 'Set your pool available for :', label_html: { class: 'label_form' }, placeholder: "Date" %></div><div class="col-xs-2" style='margin-top: 25px;'>
      <%= f.hidden_field :end_date, value: params[:start_date], id: :end_date_field %>
      <%= f.hidden_field :pool_id, value: params[:pool_id] || @pool.id %>
      <%= f.button :submit, "Mark as available", class: "btn btn-success" %></div>
      <% end %>
    </div>
  </div>
</div>
<div class="container" id="#calendar-view">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <%= month_calendar events: @agendas do |date, agendas| %>
       <%= date %>
       <% agendas.each do |agenda| %>
        <div id='available_day'>
          <%= "Available day" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>



  <%= javascript_tag do %>
  $(document).ready(function(){

    $('#agenda_start_date').datepicker({
      autoclose: true,
      format: 'dd/mm/yyyy',
      startDate: 'd'
      });

    $('#new_agenda').submit(function() {
      if($('#agenda_start_date').val() !== '') {
        filled_day = $('#agenda_start_date').val().split('/').reverse().join('-');
        $(".day:contains('" + filled_day + "')").addClass('has-events');
        $(".day:contains('" + filled_day + "')").append('Available day');
        $("#end_date_field").val($('#agenda_start_date').val());
      }
    });
  });
    <% end %>
  <% end %>

app/views/pools/edit.html.erb
<%= render 'pool_form' %>

app/views/pools/index.html.erb
<div class="container-fluid pool-cards">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-8 nopadding">
      <div class="col-xs-12 nopadding">
        <div class="header-filter">
          <%= render 'search_form' %>
        </div>
      </div>
      <div class="col-xs-12 v-scroll nopadding">
        <% @pools.each do |pool| %>
          <div class="col-xs-12 col-sm-6 col-md-6 pool-card" id="<%= pool.id %>">
            <%= render "pool_card", pool: pool %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-4 nopadding">
      <div id="map"></div>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        console.log(<%= raw @markers.to_json %>);
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length <= 1) {
          handler.getMap().setZoom(11);
        }
      });

      $('#search-submit').on('click', function(e){
        e.preventDefault();
        var my_url = window.location['origin'] + '/searchjson?' + 'location=' + '<%= @location %>' + '&max_price=' + $('#max-price').val() + '&range=' + $('#range').val();
        if ($('#max-price').val() != '' || $('#range').val() != '') {
          $.ajax({
            type: "GET",
            url: my_url,
            success: function(data) {
              var hash_pool = JSON.parse(data);
              $('.pool-card').show();
              $.each(hash_pool, function(index, value) {
                $('#' + value['id']).hide();
              });
            },
            error: function(jqXHR) {
              console.error(jqXHR.responseText);
            }
          });
        }
      });

      $('#reset-filter').on('click', function(e){
        e.preventDefault();
        $('.pool-card').show();
        $('#max-price').val('');
        $('#range').val('');
      });

      $('.avatar-bordered').on('click', function (e){
        e.preventDefault();
        window.location.replace(window.location['origin'] + '/users/' + this.id);
      });
    });
  <% end %>
<% end %>

app/views/pools/new.html.erb
<%= render 'pool_form' %>

app/views/pools/searchjson.html.erb
<%= raw @ids.to_json %>

app/views/pools/show.html.erb
<!-- app/views/pools/show.html.erb -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= @pool.photos? ? cl_image_path(@pool.photos.first.path) : image_path('barcelona_pool.jpg') %>); background-size: cover; background-position: center;">
</div>

<!-- Summary + booking form -->

<div class="container paddind-summary">
  <div class="row">
    <div class="col-xs-12 col-sm-8">
      <div class="summary">
        <div class="profile-picture text-center">
          <%= link_to user_path(@pool.user) do %>
            <% if @pool.user.avatar? %>
              <%= cl_image_tag @pool.user.avatar.path, class: 'avatar-big' %>
            <% end %>
          <% end %>
          <p style="font-size: 16px"><strong><%= @pool.user.first_name %></strong></p>
        </div>
        <div class="pool-description">
          <h1><%= @pool.title %></h1>
          <p><%= @pool.location %>&nbsp;&nbsp;&nbsp;<% unless @pool.average_rating.nil? then @pool.average_rating.round.times do %>
            <i class="fa fa-star" style="color: #EEBD2D" aria-hidden="true"></i>
          <% end %>
          <% (5 - @pool.average_rating.round).times do %>
            <i class="fa fa-star-o" aria-hidden="true"></i>
          <% end %>
           <% end %>
          </p>
          <div class="row text-center pool-infos">
            <div class="col-xs-4">
              <p><strong>Dimensions&nbsp;:</strong></p>
              <p>
                <%= @pool.width %> x <%= @pool.length %> x <%= @pool.depth %>m
              </p>
            </div>
            <div class="col-xs-4">
              <p><strong>Shape&nbsp;:</strong></p>
              <p><%= @pool.shape %></p>
            </div>
            <div class="col-xs-4">
              <p><strong>Water type&nbsp;:</strong></p>
              <p><%= @pool.water_type %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%= render "bookings/bookingform", pool: @pool %>
    </div>
  </div>
</div>

<!-- Description -->

<div class="description">
  <div class="container">
    <div class="row">
      <div class="col-xs-8">
      <h3><strong>About this pool</strong></h3>
        <p><%= @pool.description %></p>
        <p>
          <strong>Equipments&nbsp;: </strong><%= @pool.equipments %>
        </p>
      </div>
    </div>
  </div>
</div>

<!-- Customer reviews -->

<div class="container">
  <h3><%= pluralize @pool.nb_booking_comment, 'commentaire' %>&nbsp;&nbsp;&nbsp;<% unless @pool.average_rating.nil? then @pool.average_rating.round.times do %>
            <i class="fa fa-star" style="color: #EEBD2D" aria-hidden="true"></i>
          <% end %>
          <% (5 - @pool.average_rating.round).times do %>
            <i class="fa fa-star-o" aria-hidden="true"></i>
          <% end %>
          <% end %>
  </h3>
  <%= render 'bookings/booking_review' %>
</div>

<!-- This JS code transfers the logic behind every Datepicker / Timepicker from Ruby -->

<% content_for(:after_js) do %>
<%= javascript_tag do %>
$(document).ready(function(){
  var agendas = <%= raw @agendas %>;
  var unavailable_slots = <%= raw @unavailable_slots.to_json %>;

  if(agendas.length === 0) { $('#datepicker_error').show(); }

  $('#booking_date').datepicker({
    autoclose: true,
    format: 'dd/mm/yyyy',
    startDate: 'd',
    datesDisabled: <%= raw @final %>
  });


  $('#booking_date').on('change', function() {
  $('#datepicker_error').hide();
  $('#customer_error').hide();
  $('#date_error').hide ();
  $('#time_error').hide();
  $('.available').removeClass('selected');
  $('#hours-full-container').show();
  $('#booking_start_time').toggle().val('');
  $('#booking_end_time').toggle().val('');

  $('.timeslot').removeClass('unavailable').addClass('available');
    if (unavailable_slots[$(this).val()]) {
      unavailable_slots[$(this).val()].forEach(function(a){
        $('#' + a[0].slice(0,2)).removeClass('available').addClass('unavailable');
    });
    }

    $('.available').on('click', function() {
      $('.available').removeClass('selected');
      start_time = String(parseInt(this.id)).length === 2 ? String(parseInt(this.id)) + ':00' : '0' + String(parseInt(this.id)) + ':00';
      end_time = (String(parseInt(this.id) + 2)).length === 2 ? String(parseInt(this.id) + 2) + ':00' : '0' + String(parseInt(this.id) + 2) + ':00';
      $(this).toggleClass('selected');
      $('#booking_start_time').toggle().val(start_time);
      $('#booking_end_time').toggle().val(end_time);
    });

    if ($('.unavailable').length === 6) {
      $('#customer_error').show();
    }
  });

$("#submit_bookings").on('click', function(e) {
  $('#date_error').hide ();
  $('#time_error').hide();
  $('#customer_error').hide();
  e.preventDefault();

  if ($('#booking_date').val() === "") {
    $('#date_error').show();
  }
  else if($('#booking_date').val() !== "" && $('#booking_start_time').val() === "") {
    $('#time_error').show();
  }
  else if($('#booking_date').val() !== "" && $('#booking_start_time').val() !== "") {
   $('#new_booking').submit();
  }
});
});
<% end %>
<% end %>