config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root 'pages#home'
  resources :pools, except: [:destroy] do
    get 'agendas' => 'pools#availability'
    resources :agendas, only: :create
  end
  get 'searchjson' => 'pools#searchjson'
  resources :users, except: [:index, :destroy] do
    get 'bookings' => 'users#bookings'
    get 'my-pools' => 'users#pools'
  end
  resources :bookings, except: [:destroy] do
    post 'cancel' => 'bookings#cancel'
    post 'pay' => 'bookings#pay'
    post 'accept' => 'bookings#accept'
    post 'reject' => 'bookings#reject'
  end
  require "sidekiq/web"
    mount Sidekiq::Web => '/sidekiq'
end

app/models/booking.rb
class Booking < ActiveRecord::Base

  belongs_to :pool
  belongs_to :user

  validates :date, :start_time, :end_time, presence: true

  def isValidForSaving?
    # Fetch necessary instances & variables related to the booking passed in argument
    pool = Pool.find(self.pool_id)
    @agendas_for_this_pool = Agenda.where('pool_id = ?', pool.id)
    booking_date_instance = instancifyDate(self.date)

    # 1st check : is available in Agendas -- STARTDATE
    @agendas_for_this_pool.map{ |a| [instancifyDate(a.start_date), instancifyDate(a.end_date)] }.each do |d|
      return true if (booking_date_instance >= d[0] && booking_date_instance <= d[1])
    end
    false

    # 2nd check : Doesn't overlap any other booking

    # all_bookings_for_this_pool_at_this_date = Booking.where("pool_id = ? AND date = ?", pool.id, self.date)
  end

  def instancifyDate(date)
    date_array = date.split('/').map { |d| d.to_i }
    Date.new(date_array[2], date_array[1], date_array[0])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :cancel, :pay, :accept, :reject, :review]

  def new
    @booking = Booking.new
  end

  def index
    @bookings = Booking.all
  end

  def create
    # Create Booking Instance with proper parameters
    @booking = Booking.new(booking_params)
    @pool = Pool.find(params[:booking][:pool_id])

    @booking.status = "created"
    @booking.user = current_user
    @booking.price = @pool.price
    @booking.pool = @pool

    if @booking.isValidForSaving? && @booking.save
      redirect_to user_bookings_path(current_user.id)
    else
      render 'pools/show'
    end
  end

  def show
  end

  def edit
  end

  def update
    set_booking
    @booking.update(booking_params)
    redirect_to user_bookings_path(current_user)
  end

  def cancel
    @booking.status = "cancelled"
    @booking.save

    redirect_to user_bookings_path(current_user)
  end

  def pay
    @booking.status = "paid"
    @booking.save

    redirect_to user_bookings_path(current_user)
  end

  def accept
    @booking.status = "accepted"
    @booking.save

    redirect_to user_bookings_path(current_user)
  end

  def reject
    @booking.status = "rejected"
    @booking.save

    redirect_to user_bookings_path(current_user)
  end

  private

  def set_booking
    unless params[:id].nil?
      @booking = Booking.find(params[:id])
    else
      @booking = Booking.find(params[:booking_id])
    end
  end

  def booking_params
    params.require(:booking).permit(:date, :start_time, :end_time, :customer_rating, :customer_comment, :booking_rating, :booking_comment)
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking_review.html.erb
<div class="row">
  <% @pool.bookings.each do |booking| %>
    <% unless booking.booking_rating.nil? %>
    <div class="col-xs-12 col-sm-8">
      <div class="pool-review">
        <div class="profile-picture text-center">
          <%= cl_image_tag booking.user.avatar.path, class: 'avatar-big' %>
          <p><%= booking.user.first_name %></p>
        </div>
        <div class="pool-review-content">
          <p><%= booking.date %>&nbsp;&nbsp;&nbsp;
            <% booking.booking_rating.times do %>
              <i class="fa fa-star" style="color: #EEBD2D" aria-hidden="true"></i>
            <% end %>
            <% (5 - booking.booking_rating).times do %>
              <i class="fa fa-star-o" aria-hidden="true"></i>
            <% end %>
          </p>
          <p><%= booking.booking_comment %></p>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/bookings/_bookingform.html.erb
<div class="col-xs-12" id="datepicker_error" style="display: none">Sorry, there are no available dates for this pool<br>
<%= link_to 'Back to the list of pools', pools_path  %>
</div>
<%= simple_form_for @booking do |f| %>

<%= f.input :date, label: 'Book your pool for :', label_html: { class: 'label_form' }, placeholder: "Date" %>
<%= f.hidden_field :start_time, label: 'Starting at :', label_html: { class: 'label_form' } %>
<%= f.hidden_field :end_time, label: 'Ending at :', label_html: { class: 'label_form' } %>
<div class="col-xs-12" id="hours-full-container">
<div class="row">
  <div class="col-xs-12" id="hourly-title">
    Pick your reservation timeslot&nbsp;:
  </div>
</div>
<div class="row">
  <div class="col-xs-12" id="hours-container">
    <div class="col-xs-4" id="timeslot"><div class="col-xs-12 timeslot unavailable" id='08'>8h - 10h</div></div><div class="col-xs-4" id="timeslot"><div class="col-xs-12 timeslot unavailable" id='10'>10h - 12h</div></div>
    <div class="col-xs-4" id="timeslot"><div class="col-xs-12 timeslot unavailable" id='12'>12h - 14h</div></div><div class="col-xs-4" id="timeslot"><div class="col-xs-12 timeslot unavailable" id='14'>14h - 16h</div></div><div class="col-xs-4" id="timeslot"><div class="col-xs-12 timeslot unavailable" id='16'>16h - 18h</div></div>
    <div class="col-xs-4" id="timeslot"><div class="col-xs-12 timeslot unavailable" id='18'>18h - 20h</div></div>
  </div>
  </div></div>
  <div class="col-xs-12" id="hours-submit">
  <%= f.hidden_field :pool_id, value: params[:id] || @booking.pool_id %>
  <%= f.button :button, "Book now!", id: "submit_bookings", class: "btn btn-danger", style: 'width:100%' %>
  </div>
  <div class="col-xs-12" id="customer_error" style="display: none">Sorry, there are no available slots for this day.</div>
  <div class="col-xs-12" id="date_error" style="display: none">Please fill in a date before validation</div>
  <div class="col-xs-12" id="time_error" style="display: none">Please chose an available slot before validation</div>
</div>
</div>
</div>
<% end %>

<!-- --TODO-- find a way to secure the transaction without passing pool_id in hidden field -->

app/views/bookings/_form.html.erb
<%= simple_form_for @booking do |f|%>
<%= f.input :start_date %>
<%= f.input :end_date %>
<%= f.hidden_field :price, value: @pool.price %>
<%= f.hidden_field :status, value: "created" %>
<%= f.hidden_field :user, value: current_user %>
<%= f.hidden_field :pool, value: @pool %>
<%= f.button :submit %>
<% end %>

app/views/bookings/_index.html.erb
<h1>My Bookings</h1>

<ul>
<% @bookings.each do |booking| %>
  <li><%= booking.user.first_name + " " + booking.user.last_name + " booked a pool to " + booking.pool.user.first_name + " " + booking.user.last_name %></li>
<% end %>
</ul>

app/views/bookings/_new.html.erb
<h1>Create a booking</h1>

<%= render 'form' %>

app/views/bookings/new.html.erb
<h1>Create a booking</h1>

<%= render 'form' %>