config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root 'pages#home'
  resources :pools, except: [:destroy] do
    get 'agendas' => 'pools#availability'
    resources :agendas, only: :create
  end
  get 'searchjson' => 'pools#searchjson'
  resources :users, except: [:index, :destroy] do
    get 'bookings' => 'users#bookings'
    get 'my-pools' => 'users#pools'
  end
  resources :bookings, except: [:destroy] do
    post 'cancel' => 'bookings#cancel'
    post 'pay' => 'bookings#pay'
    post 'accept' => 'bookings#accept'
    post 'reject' => 'bookings#reject'
  end
  require "sidekiq/web"
    mount Sidekiq::Web => '/sidekiq'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings
  has_many :pools
  has_attachment :avatar

  # validates :first_name, :last_name, :birth_date, :address, :phone, :email, presence: true
  #
  #

  def count_pending_actions
    # count actions pour navbar
    # les created dans le cas ou qqun a fait une résa sur ma pool
    # les accepted dans le cas ou j'ai fait une résa

    count = 0
    count += Booking.all.where('user_id = ? AND status = "accepted"', self.id).size unless @bookings.nil?

    Booking.all.each do |booking|
      count += 1 if booking.pool.user_id == self.id && booking.status == "created"
    end

  return count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    p @user
    p current_user
    if @user == current_user
      render :show
    else
      render :open_profile
    end
  end

  def update
    @user = User.find(current_user)
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :show
    end
  end

  def bookings
    # Get Customer bookings for the user :
    @customer_bookings = Booking.where("user_id = #{current_user.id}")

    # Get Owner reservations for the user :
    @owned_pools = Pool.where("user_id = #{current_user.id}")
    @owner_bookings = []
    @owned_pools.each do |pool|
      @owner_bookings << Booking.where("pool_id = #{pool.id}") unless Booking.where("pool_id = #{pool.id}").nil?
    end
    @owner_bookings.flatten!
  end

  def pools
    @pools = Pool.where("user_id = #{current_user.id}")
    if params.has_key?(:pool_id)
      @pool = Pool.find(params[:pool_id].to_i)
      @show_modale = true
    else
      @pool = Pool.new
    end
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :birth_date, :address, :bio, :phone, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bookings_customer_current.html.erb
<div class="booking-owner-line">
  <div class="avatar-owner-line">
    <% if booking.user.avatar? %>
      <%= cl_image_tag booking.user.avatar.path, class: 'avatar-large' %>
    <% end %>
  </div>
  <div class="content-owner-line">
    <p>
      You booked <strong><%= booking.pool.title %></strong> (<%= booking.pool.location %>)
      on <%= booking.date %></strong> - from <%= booking.start_time %> to <%= booking.end_time %>
    </p>
  </div>
  <div class="status-owner-line">
    <% if booking.status == "paid" %>
      <em><p>Payment received !</p></em>
    <% else %>
      <em><p>Currently awaiting your payment !</p></em>
    <% end %>
  </div>
  <div class="action-owner-line">
    <% if booking.status == "paid" %>
    <%= button_to 'Cancel', booking_cancel_path(booking), method: :post, class: "btn btn-danger width-btn" %>
    <% else %>
    <%= button_to 'Pay', booking_pay_path(booking), method: :post, class: "btn btn-primary width-btn" %>
    <% end %>
  </div>
</div>

app/views/users/_bookings_customer_new.html.erb
<div class="booking-owner-line">
  <div class="avatar-owner-line">
    <% if booking.user.avatar? %>
      <%= cl_image_tag booking.user.avatar.path, class: 'avatar-large' %>
    <% end %>
  </div>
  <div class="content-owner-line">
    <p>
      You booked <strong><%= booking.pool.title %></strong> (<%= booking.pool.location %>)
      on <%= booking.date %></strong> - from <%= booking.start_time %> to <%= booking.end_time %>
    </p>
  </div>
  <div class="status-owner-line">
    <em><p>Awaiting owner to accept your request !</p></em>
  </div>
  <div class="action-owner-line">
    <%= button_to 'Cancel', booking_cancel_path(booking), method: :post, class: "btn btn-danger width-btn" %>
  </div>
</div>

app/views/users/_bookings_customer_past.html.erb
<div class="booking-owner-line">
  <div class="avatar-owner-line">
    <% if booking.user.avatar? %>
      <%= cl_image_tag booking.user.avatar.path, class: 'avatar-large' %>
    <% end %>
  </div>
  <div class="content-owner-line">
    <p>
      You booked <strong><%= booking.pool.title %></strong> (<%= booking.pool.location %>)
      on <%= booking.date %></strong> - from <%= booking.start_time %> to <%= booking.end_time %>
    </p>
  </div>
  <div class="status-owner-line">
    <% if booking.status == "rejected" %>
      <em><p>Owner has rejected your request ! Too bad :(</p></em>
    <% elsif booking.status == "cancelled" %>
      <em><p>Your request has been cancelled !</p></em>
    <% elsif booking.status == "closed" && booking.booking_comment.nil? %>
      <em><p>Please, add a review on your host</p></em>
    <% else %>
      <em><p>Thank you for your review !</p></em>
    <% end %>
  </div>
  <div class="action-owner-line">
    <% if booking.status == "closed" && booking.booking_comment.nil? %>
      <button type="button" id="create_pool" class="btn btn-primary" style="width: 100px; margin-bottom: 10px;" data-toggle="modal" data-target="#reviewModalCustomer<%= booking.id %>">Review</button>
    <% end %>
    <br>
  </div>
</div>

<div class="modal fade" id="reviewModalCustomer<%= booking.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Rate your customer and add a comment !</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(booking) do |f| %>
          <%= f.error_notification %>
          <%= f.input :booking_rating %>
          <%= f.input :booking_comment %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.button :submit, class: 'btn btn-success', id: 'submit-button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_bookings_owner_current.html.erb
<div class="booking-owner-line">
  <div class="avatar-owner-line">
    <% if booking.user.avatar? %>
      <%= cl_image_tag booking.user.avatar.path, class: 'avatar-large' %>
    <% end %>
  </div>
  <div class="content-owner-line">
    <p>
      <strong><%= booking.user.first_name %></strong> booked
      <strong><%= booking.pool.title %></strong> (<%= booking.pool.location %>)
      on <%= booking.date %></strong> - from <%= booking.start_time %> to <%= booking.end_time %>
    </p>
  </div>
  <div class="status-owner-line">
    <% if booking.status == "paid" %>
      <em><p>Payment received !</p></em>
    <% else %>
      <em><p>Currently awaiting payment from customer</p></em>
    <% end %>
  </div>
  <div class="action-owner-line">
    <%= button_to 'Cancel', booking_cancel_path(booking), method: :post, class: "btn btn-danger width-btn" %>
  </div>
</div>

app/views/users/_bookings_owner_new.html.erb
<div class="booking-owner-line">
  <div class="avatar-owner-line">
    <% if booking.user.avatar? %>
      <%= cl_image_tag booking.user.avatar.path, class: 'avatar-large' %>
    <% end %>
  </div>
  <div class="content-owner-line">
    <p>
      <strong><%= booking.user.first_name %></strong> booked
      <strong><%= booking.pool.title %></strong> (<%= booking.pool.location %>)
      on <%= booking.date %></strong> - from <%= booking.start_time %> to <%= booking.end_time %>
    </p>
  </div>
  <div class="status-owner-line">
    <em><p>Currently waiting for you !</p></em>
  </div>
  <div class="action-owner-line">
    <%= button_to 'Accept', booking_accept_path(booking), method: :post, class: "btn btn-primary width-btn" %>
    <br>
    <%= button_to 'Reject', booking_reject_path(booking), method: :post, class: "btn btn-danger width-btn" %>
  </div>
</div>

app/views/users/_bookings_owner_past.html.erb
<div class="booking-owner-line">
  <div class="avatar-owner-line">
    <% if booking.user.avatar? %>
      <%= cl_image_tag booking.user.avatar.path, class: 'avatar-large' %>
    <% end %>
  </div>
  <div class="content-owner-line">
    <p>
      <strong><%= booking.user.first_name %></strong> booked
      <strong><%= booking.pool.title %></strong> (<%= booking.pool.location %>)
      on <%= booking.date %></strong> - from <%= booking.start_time %> to <%= booking.end_time %>
    </p>
  </div>
  <div class="status-owner-line">
    <% if booking.status == "rejected" %>
      <em><p>Rejected !</p></em>
    <% elsif booking.status == "cancelled" %>
      <em><p>Cancelled !</p></em>
    <% elsif booking.status == "closed" && booking.customer_comment.nil? %>
      <em><p>Please, add a review on your customer</p></em>
    <% else %>
      <em><p>Thank you for your review !</p></em>
    <% end %>
  </div>
  <div class="action-owner-line">
    <% if booking.status == "closed" && booking.customer_comment.nil?  %>
      <button type="button" id="create_pool" class="btn btn-primary" style="width: 170px; margin-bottom: 10px;" data-toggle="modal" data-target="#reviewModalOwner<%= booking.id %>">Review</button>
    <% end %>
    <br>
  </div>
</div>

<div class="modal fade" id="reviewModalOwner<%= booking.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Rate your owner and add a comment !</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(booking) do |f| %>
          <%= f.error_notification %>
          <%= f.input :customer_rating %>
          <%= f.input :customer_comment %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.button :submit, class: 'btn btn-success', id: 'submit-button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/bookings.html.erb
<div class="container-full grey-container">
  <div class="tabs">
    <a class="tab active" id="customer" href="#">
      <h3>Your Dives</h3>
    </a>
    <a class="tab" id="owner" href="#">
      <h3>Your pool requests</h3>
    </a>
  </div>

<!-- Customer bookings : NEW / CURRENT / PAST -->

  <div class="main-booking bg-grey active" id="display_customer">
    <div class="bg-white container-bookings">
      <div class="new-bookings">
        <strong><h3 style="border-bottom: 1px solid #cacccd;">Your new dives</h3></strong>
        <% @customer_bookings.each do |booking| %>
          <% if booking.status == "created" then %>
            <%= render 'users/bookings_customer_new', booking: booking %>
          <% end %>
        <% end %>
      </div>
      <div class="current-bookings">
        <strong><h3 style="border-bottom: 1px solid #cacccd;">Your current dives</h3></strong>
        <div class="booking-avatar-owner">
          <% @customer_bookings.each do |booking| %>
            <% if (booking.status == "accepted" || booking.status == "paid") then %>
              <%= render 'users/bookings_customer_current', booking: booking %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="past-bookings">
        <strong><h3 style="border-bottom: 1px solid #cacccd;">Your past dives</h3></strong>
        <div class="booking-avatar-owner">
          <% @customer_bookings.each do |booking| %>
            <% if (booking.status != "accepted" && booking.status != "paid" && booking.status != "created") then %>
              <%= render 'users/bookings_customer_past', booking: booking %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<!-- Owner bookings : NEW / CURRENT / PAST -->

  <div class="main-booking bg-grey" id="display_owner">
    <div class="bg-white container-bookings">
      <div class="new-bookings">
        <strong><h3 style="border-bottom: 1px solid #cacccd;">New pool requests</h3></strong>
        <% @owner_bookings.each do |booking| %>
          <% if booking.status == "created" then %>
            <%= render 'users/bookings_owner_new', booking: booking %>
          <% end %>
        <% end %>
      </div>
      <div class="current-bookings">
        <strong><h3 style="border-bottom: 1px solid #cacccd;">Current pool requests</h3></strong>
        <div class="booking-avatar-owner">
          <% @owner_bookings.each do |booking| %>
            <% if (booking.status == "accepted" || booking.status == "paid") then %>
              <%= render 'users/bookings_owner_current', booking: booking %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="past-bookings">
        <strong><h3 style="border-bottom: 1px solid #cacccd;">Closed pool requests</h3></strong>
        <div class="booking-avatar-owner">
          <% @owner_bookings.each do |booking| %>
            <% if (booking.status != "accepted" && booking.status != "paid" && booking.status != "created") then %>
              <%= render 'users/bookings_owner_past', booking: booking %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>



<% content_for :after_js do %>
  <%= javascript_tag do %>
  $(document).ready(function(){
    if ( <%= !@show_modale.nil? %> ){
      $('#myModal').modal('show');
    };
  });
  <% end %>
<% end %>

app/views/users/open_profile.html.erb
<div class="wrapper-content">
  <div class="container-content">
    <div class="avatar-profile">
      <% if @user.avatar? %>
        <%= cl_image_tag @user.avatar.path, class: "avatar-big"%>
      <% end %>
      <p><strong><%= @user.first_name %> <%= @user.last_name %></strong></p>
    </div>
    <div class="content-profile">
        <p>Bio : <%= @user.bio %></p>
    </div>
    <div class="picture-pools">
      <% @user.pools.each do |pool| %>
        <div class="col-xs-4 nopadding">
          <%= link_to pool_path(pool) do %>
            <% if pool.photos? %>
              <%= cl_image_tag pool.photos.first.path, class: "small-image" %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/pools.html.erb
<div class="container" style="padding-bottom: 20px">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
      <button type="button" id="create_pool" class="btn btn-primary" style="width: 100%; margin-top: 20px; margin-bottom: 20px;" data-toggle="modal" data-target="#myModal">Add a pool</button>
      <% @pools.each do |pool| %>
        <%= render "pools/owner_pool_card", pool: pool %>
      <% end %>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Describe and create your pool !</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@pool) do |f| %>
          <%= f.error_notification %>
          <%= f.input :title %>
          <%= f.input :description %>
          <%= f.input "address", input_html: { id: "user_input_autocomplete_address", placeholder: "Start typing your address..." } %>
          <%= f.input :location, as: :hidden, input_html: { id: "locality" } %>
          <div class="button-inline">
            <%= f.input :width %>
            <%= f.input :length %>
            <%= f.input :depth %>
          </div>
          <div class="button-inline">
            <%= f.input :shape %>
            <%= f.input :water_type %>
            <%= f.input :price %>
          </div>
          <%= f.input :equipments %>
          <%= f.input :photos, as: :attachinary, class: 'list-unstyled' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.button :submit, class: 'btn btn-success', id: 'submit-button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<% content_for :after_js do %>
  <%= javascript_tag do %>
  $(document).ready(function(){
    if ( <%= !@show_modale.nil? %> ){
      $('#myModal').modal('show');
    };
  });
  <% end %>
<% end %>

app/views/users/show.html.erb
<% if current_user.id == @user.id %>
<div class="col-xs-12" style="padding-bottom: 20px; background-color: rgb(220, 220, 220);">
  <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-sm-offset-3" style="padding: 50px; background-color: white; margin-top: 50px; border-radius: 4px;">
    <h1>Your profile :</h1><br>
    <div class="row">
        <%= simple_form_for @user do |f| %>
        <%= f.input :first_name, input_html: { value: "#{@user.first_name}" } %>
        <%= f.input :last_name, input_html: { value: "#{@user.last_name}" } %>
        <%= f.input :email, input_html: { value: "#{@user.email}" } %>
        <%= f.input :birth_date, input_html: { value: "#{@user.birth_date}" } %>
        <%= f.input :address, input_html: { value: "#{@user.address}" } %>
        <%= f.input :bio, input_html: { value: "#{@user.bio}" } %>
        <%= f.input :phone, input_html: { value: "#{@user.phone}" } %>
        <%= f.input :avatar, as: :attachinary %>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>
<% else %>
<div class="col-xs-12" style="padding-bottom: 20px;">
Sorry, this page is not available for you. Please log in again.
</div>
<% end %>