config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root 'pages#home'
  resources :pools, except: [:destroy] do
    get 'agendas' => 'pools#availability'
    resources :agendas, only: :create
  end
  get 'searchjson' => 'pools#searchjson'
  resources :users, except: [:index, :destroy] do
    get 'bookings' => 'users#bookings'
    get 'my-pools' => 'users#pools'
  end
  resources :bookings, except: [:destroy] do
    post 'cancel' => 'bookings#cancel'
    post 'pay' => 'bookings#pay'
    post 'accept' => 'bookings#accept'
    post 'reject' => 'bookings#reject'
  end
  require "sidekiq/web"
    mount Sidekiq::Web => '/sidekiq'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Your footer code -->
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <ul class="list-inline">
          <li>
            <a href="#" id="ythover">
              <i class="fa fa-youtube"></i>
            </a>
          </li>
          <li>
            <a href="#" id="fbhover">
              <i class="fa fa-facebook"></i>
            </a>
          </li>
          <li>
            <a href="#" id="twhover">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
          <li>
            <a href="#" id="insthover">
              <i class="fa fa-instagram"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-xs-8 text-right" id="footer-text">
        <p>AirPnD challenge @ LeWagon</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo2.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to user_bookings_path(current_user), class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue"><%= current_user.count_pending_actions %></div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% unless current_user.avatar.nil? %>
          <strong><span style="font-size: 12px;"><%= current_user.first_name %></span></strong>
          <%= cl_image_tag current_user.avatar.path, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %><% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "My Profile" %><!-- --TODO-- find the right fa icon -->
              <% end %>
            </li>
            <li>
              <%= link_to user_bookings_path(current_user) do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "My Bookings" %><!-- --TODO-- find the right fa icon -->
              <% end %>
            </li>
            <li>
              <%= link_to user_my_pools_path(current_user) do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Manage my pools" %><!-- --TODO-- find the right fa icon -->
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Register link -->
      <%= link_to t(".sign_in", default: "Register"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>
  </div>
</div>